name: Run example
run-name: ${{ github.actor }} is running regression tests
on: 
  workflow_dispatch:
    inputs:
      package:
        description: "Package either 'docker://' or 'https://'. Example: 'https://s3.amazonaws.com/clickhouse-builds/23.3/.../package_release/clickhouse-common-static_23.3.1.64_amd64.deb', or 'docker://clickhouse/clickhouse-server'"
        required: true
        type: string
        default: docker://clickhouse/clickhouse-server
      version:
        description: "Expected version. Example: 23.3.1.64"
        required: true
        type: string
        default: 23.2.2.20

env:
  PYTHONIOENCODING: utf-8
  clickhouse_binary_path: ${{ inputs.package }}
  version: ${{ inputs.version }}
  artifacts: ${{ inputs.artifacts }}
  args: --test-to-end
    --local
    --collect-service-logs 
    --output ${{ vars.OUTPUT }} 
    --parallel ${{ vars.PARALLEL }}
    --attr project="$GITHUB_REPOSITORY" project.id="$GITHUB_REPOSITORY_ID" user.name="$GITHUB_ACTOR" version="${{ inputs.version }}" package="${{ inputs.package }}" repository="https://github.com/Altinity/clickhouse-regression" commit.hash="$GITHUB_SHA" job.id="$GITHUB_RUN_ID" job.url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" arch="${{ vars.ARCH }}"
    --log raw.log
  artifact_paths: |
    ./report.html
    ./*.log.txt
    ./*.log
    ./*.html
    ./*/_instances/*.log
    ./*/_instances/*/logs/*.log
    ./*/*/_instances/*/logs/*.log
    ./*/*/_instances/*.log
    
jobs:
  example:
    runs-on: [self-hosted, x86_64]
    env:
      SUITE: example
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: .github/setup.sh

      - name: Run ${{ env.SUITE }} suite
        run: python3
              -u ${{ env.SUITE }}/regression.py
              --clickhouse-binary-path ${{ env.clickhouse_binary_path }}
              --clickhouse-version ${{ env.version }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: example-artifacts
          path: ${{ env.artifact_paths}}
